#title: Ruben Raposo Portfolio
#author: Ruben Raposo
#email: your-email@domain.com
#description: > # this means to ignore newlines until "baseurl:"
 # Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
# social links
#twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
#github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
#show_excerpts: true # set to false to remove excerpts on the homepage
#theme: jekyll-theme-cayman


title: Ruben Raposo # your name (or website title) here
author: Ruben Raposo
logo: "/images/1516823704353.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Dynamics CRM Consultant
  <br><br>
  Portugal
  <br><br>
  <a href="hhttps://www.linkedin.com/in/ruben-raposo-77557b96/">View My LinkedIn Profile</a>     
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
